### ISSUE TITLE
Do not add password arg to user state if does not exist in pillar data

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-describe#42]
The user describe runner will generate a sls file like so:

```
user-ch3ll:
  user.present:
  - name: ch3ll
  - uid: 1000
  - gid: 1000
  - allow_uid_change: true
  - allow_gid_change: true
  - home: /home/ch3ll
  - shell: /usr/bin/zsh
  - groups:
    - ch3ll
    - lp
    - network
    - power
    - sys
    - wheel
  - password: '{{ salt["pillar.get"]("users:ch3ll","*") }}'
  - date: 18590
  - mindays: 0
  - maxdays: 99999
  - inactdays: -1
  - expire: -1
  - createhome: true
  - fullname: Megan Wilhite
```

If `users:ch3ll` is not set in pillar, it will still try changing the password, which would be unexpected for a user who does not know that is a requirement for the user state. We should make this optional and only set the password argument if `users:ch3ll` is in pillar data. Most likely we will want to handle this with jinja.
